name: test rickstaa/action-get-semver
on:
  push:
    branches:
      - main
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-get-semver@v1
        id: get_semver
        with:
          bump_level: "minor"
      - name: Print semver
        run: |
          echo "Current version: ${{ steps.get_semver.outputs.current_version  }}"
          echo "Next version: ${{ steps.get_semver.outputs.next_version }}"
