name: test rickstaa/action-create-tag
on:
  push:
    branches:
      - main
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: rickstaa/action-create-tag@latest
        with:
          tag: "test-tag-1"
          message: "Test tag 1"
