name: PRB0t check action
on: [pull_request]

jobs:
  prB0t_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Display context
        run : echo '${{ toJSON(github) }}'

      # Check whether PRB0T was used.
      - uses: rickstaa/check-prb0t-action@main
        id: prb0t_check

      # Print result using the env variable.
      -  run: |
          echo "${{ env.USED_PRB0T }}"

      # Print result using the action output.
      - run: |
          echo "PRB0t used: ${{ steps.prb0t_check.outputs.used_prb0t }}"
