name: reviewdog
on: [pull_request, push]
jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-black@add-auto-format-option
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check, github-check].
          reporter: github-check
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with warning.
          level: warning
