name: reviewdog
on: [push, pull_request]
jobs:
  black-normal:
    name: runner / black(exp)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Lint black
        uses: psf/black@stable
        with:
          args: "-q ."
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: gofmt
      - name: Check if formatting was successful
        run: |
          changed_files=$(git status --porcelain | wc -l)
          if [[ ${changed_files} -eq 0 ]]; then
            echo "No changes detected!"
          else
            echo "Changes detected!"
            exit 1
          fi
